#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_CLOCK_SOURCE_INTERNAL // 21.921792 Mhz DCO referenced to internal REFO
// #define CONFIG_CLOCK_SOURCE_CRYSTAL // 25 Mhz XT2 crystal

// #define CONFIG_ROUTE_ACLK_TO_PIN // must "unplug" op amp buffers by disconnecting JP1

// UART baudrate specification:
// N = SMCLK / BAUD
// BR0 = LSB(floor(N))
// BR1 = MSB(floor(N))
// BRS = (floor(N) - N) * 8

#if defined(CONFIG_CLOCK_SOURCE_INTERNAL)

// SMCLK = 21.921792 Mhz (clock sourced from DCO): N = 23.786666...
#define CONFIG_USB_UART_BAUDRATE 921600
#define CONFIG_USB_UART_BAUDRATE_BR0 23
#define CONFIG_USB_UART_BAUDRATE_BR1 0
#define CONFIG_USB_UART_BAUDRATE_BRS 6

// SMCLK = 21.921792 Mhz (clock sourced from DCO): N = 2283.52
#define CONFIG_TARGET_UART_BAUDRATE 9600
#define CONFIG_TARGET_UART_BAUDRATE_BR0 0xEB
#define CONFIG_TARGET_UART_BAUDRATE_BR1 0x08
#define CONFIG_TARGET_UART_BAUDRATE_BRS 4

#elif defined(CONFIG_CLOCK_SOURCE_CRYSTAL)

// SMCLK = 25/2 = 12.5 Mhz
#define CONFIG_USB_UART_BAUDRATE 2000000
#define CONFIG_USB_UART_BAUDRATE_BR0 6
#define CONFIG_USB_UART_BAUDRATE_BR1 0
#define CONFIG_USB_UART_BAUDRATE_BRS 2

// // SMCLK = 25/2 = 12.5 Mhz
// #define CONFIG_USB_UART_BAUDRATE 1000000
// #define CONFIG_USB_UART_BAUDRATE_BR0 12
// #define CONFIG_USB_UART_BAUDRATE_BR1 0
// #define CONFIG_USB_UART_BAUDRATE_BRS 4
//
// // SMCLK = 25/2 = 12.5 Mhz
// #define CONFIG_USB_UART_BAUDRATE 115200
// #define CONFIG_USB_UART_BAUDRATE_BR0 108
// #define CONFIG_USB_UART_BAUDRATE_BR1 0
// #define CONFIG_USB_UART_BAUDRATE_BRS 4
//
// // SMCLK = 25/4 = 12.5 Mhz
// #define CONFIG_USB_UART_BAUDRATE 115200
// #define CONFIG_USB_UART_BAUDRATE_BR0 54
// #define CONFIG_USB_UART_BAUDRATE_BR1 0
// #define CONFIG_USB_UART_BAUDRATE_BRS 2

// SMCLK = 25/2 = 12.5 Mhz: N = 1302.083333...
#define CONFIG_TARGET_UART_BAUDRATE 9600
#define CONFIG_TARGET_UART_BAUDRATE_BR0 0x16
#define CONFIG_TARGET_UART_BAUDRATE_BR1 0x05
#define CONFIG_TARGET_UART_BAUDRATE_BRS 1

#else // CONFIG_CLOCK_SOURCE_*
#error UART configuration error: no CONFIG_CLOCK_SOURCE_x defined
#endif // CONFIG_CLOCK_SOURCE_*

#endif

