# Available configuration options to be set in the master makefile

# Enable code for decoding the RF protocol
# 		Currently, this is disabled because it causes spurious interrupts.
#
#       TODO: setup RF pins only upon cmd to monitor RF because otherwise we
#       get spurious interrupts on RX pin
#
ifeq ($(CONFIG_ENABLE_RF_PROTOCOL_MONITORING),1)
	CFLAGS += -DCONFIG_ENABLE_RF_PROTOCOL_MONITORING
endif

# Enable listening and recording communication on I2C bus
# 		TODO: this is not currently implemented
ifeq ($(CONFIG_ENABLE_I2C_MONITORING),1)
	CFLAGS += -DCONFIG_ENABLE_I2C_MONITORING
endif

# Enable a time-keeping timer (systick)
ifeq ($(CONFIG_SYSTICK),1)
	CFLAGS += -DCONFIG_SYSTICK
endif

# Capacitor charge implemented by a PWM with a control loop around the duty-cycle
# 		The alternative is an "valve" method of raising a GPIO high and watching
#       the voltage level with ADC or comparator and pulling the GPIO low once
#       the target threshold is crossed.
#
ifeq ($(CONFIG_PWM_CHARGING),1)
	CFLAGS += -DCONFIG_PWM_CHARGING
endif
