#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_USB_UART_BAUDRATE 2000000ull
// #define CONFIG_USB_UART_BAUDRATE 1500000ull
// #define CONFIG_USB_UART_BAUDRATE 1000000ull
// #define CONFIG_USB_UART_BAUDRATE 921600ull
// #define CONFIG_USB_UART_BAUDRATE 576000ull
// #define CONFIG_USB_UART_BAUDRATE 500000ull
// #define CONFIG_USB_UART_BAUDRATE 460800ull
// #define CONFIG_USB_UART_BAUDRATE 171264ull
// #define CONFIG_USB_UART_BAUDRATE 115200ull
// #define CONFIG_USB_UART_BAUDRATE 38400ull

//#define CONFIG_TARGET_UART_BAUDRATE 9600ull
#define CONFIG_TARGET_UART_BAUDRATE 115200ull

// #define CONFIG_USB_UART_UCOS16
// #define CONFIG_TARGET_UART_UCOS16

// #define CONFIG_TIMELOG_TIMER_SOURCE TASSEL__ACLK
#define CONFIG_TIMELOG_TIMER_SOURCE TASSEL__SMCLK

//#define CONFIG_TIMELOG_TIMER_DIV 1
#define CONFIG_TIMELOG_TIMER_DIV 8
#define CONFIG_TIMELOG_TIMER_DIV_EX 1
//#define CONFIG_TIMELOG_TIMER_DIV_EX 8

// #define CONFIG_ADC_TIMER_SOURCE_ACLK
#define CONFIG_ADC_TIMER_SOURCE_SMCLK
// #define CONFIG_ADC_TIMER_SOURCE_MCLK

#define CONFIG_ADC_TIMER_DIV 8

#if defined(CONFIG_ADC_TIMER_SOURCE_ACLK)
#define CONFIG_ADC_TIMER_SOURCE_NAME ACLK
#define CONFIG_ADC_TIMER_CLK_FREQ CONFIG_ACLK_FREQ
#elif defined(CONFIG_ADC_TIMER_SOURCE_SMCLK)
#define CONFIG_ADC_TIMER_SOURCE_NAME SMCLK
#define CONFIG_ADC_TIMER_CLK_FREQ CONFIG_SMCLK_FREQ
#elif defined(CONFIG_ADC_TIMER_SOURCE_SMCLK)
#define CONFIG_ADC_TIMER_SOURCE_NAME MCLK
#define CONFIG_ADC_TIMER_CLK_FREQ CONFIG_MCLK_FREQ
#elif defined(CONFIG_ADC_TIMER_SOURCE_MCLK)
#else
#error No clock source selected for ADC timer: see CONFIG_ADC_TIMER_SOURCE_*
#endif // CONFIG_ADC_TIMER_SOURCE_*

#define CONFIG_ADC_TIMER_FREQ (CONFIG_ADC_TIMER_CLK_FREQ / CONFIG_ADC_TIMER_DIV)

// Intervals for schedulable actions: time source fixed at ACLK
#define CONFIG_ENTER_DEBUG_MODE_TIMEOUT   0xff
#define CONFIG_EXIT_DEBUG_MODE_TIMEOUT    0xff

#endif // CONFIG_H
